recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from recipes.views import recipes_home
from .views import login_view, logout_view, success_view
from recipes.views import create_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("", recipes_home, name="home"),  # Include the recipes_home view,
    path("recipes/", include("recipes.urls")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("success/", success_view, name="success"),
    path("create/", create_view, name="create"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import (
    RecipeListView,
    RecipeDetailView,
    recipes_home,
    search,
    create_view,
    about,
)

app_name = "recipes"

urlpatterns = [
    path("home/", recipes_home, name="home"),
    path("list/", RecipeListView.as_view(), name="list"),
    path("list/<int:pk>/", RecipeDetailView.as_view(), name="detail"),
    path("search/", search, name="search"),
    path("create/", create_view, name="create"),
    path("about/", about, name="about"),
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
difficulty_choices = (
    ("Easy", "Easy"),
    ("Medium", "Medium"),
    ("Intermediate", "Intermediate"),
    ("Hard", "Hard"),
)


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.PositiveIntegerField(help_text="in minutes")
    ingredients = models.CharField(max_length=300)
    difficulty = models.CharField(max_length=12, choices=difficulty_choices)
    pic = models.ImageField(upload_to="recipes", default="no_picture.jpg")

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={"pk": self.pk})

recipes/forms.py
from django import forms
from .models import Recipe

CHART_CHOICES = (("#1", "Bar chart"), ("#2", "Pie chart"), ("#3", "Line chart"))

DIFFICULTY_CHOICES = (
    ("", " "),
    ("Easy", "Easy"),
    ("Medium", "Medium"),
    ("Intermediate", "Intermediate"),
    ("Hard", "Hard"),
)


class RecipesSearchForm(forms.Form):
    recipe_name = forms.CharField(max_length=120, required=False, label="Recipe Name")
    ingredients = forms.CharField(max_length=300, required=False, label="Ingredients")
    recipe_diff = forms.ChoiceField(
        choices=DIFFICULTY_CHOICES, required=False, label="Recipe Difficulty Level"
    )
    chart_type = forms.ChoiceField(
        choices=CHART_CHOICES, required=False, label="Chart Type"
    )


class CreateRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["name", "cooking_time", "difficulty", "ingredients", "pic"]

recipes/views.py
from django.shortcuts import render, redirect  # imported by default
from django.views.generic import ListView, DetailView  # to display lists
from .models import Recipe  # to access recipe model
from django.contrib.auth.mixins import LoginRequiredMixin  # to protect class-based view
from django.contrib.auth.decorators import (
    login_required,
)  # to protect function-based view
from .forms import RecipesSearchForm, CreateRecipeForm
import pandas as pd
from .utils import get_recipename_from_id, get_chart
from django.contrib import messages

from django.db.models import Q  # Import Q object for comples queries


# Create your views here.
def recipes_home(request):
    return render(request, "recipes/recipes_home.html")


def about(request):
    return render(request, "recipes/about.html")


class RecipeListView(LoginRequiredMixin, ListView):  # class-based view
    model = Recipe  # specify model
    template_name = "recipes/main.html"  # specity template


class RecipeDetailView(LoginRequiredMixin, DetailView):  # class-based view
    model = Recipe  # specify model
    template_name = "recipes/detail.html"  # specify template


# #define function-based view - search(request)
# #keep protected
@login_required
def search(request):
    # Initialize the search form
    form = RecipesSearchForm(request.POST or None)
    recipes_df = None
    chart = None
    qs = Recipe.objects.none()  # Initialize with an empty queryset

    if request.method == "POST":
        # Check if the form is valid
        if form.is_valid():
            # Retrieve input values from the form
            recipe_name = form.cleaned_data.get("recipe_name")
            ingredients = form.cleaned_data.get("ingredients")
            recipe_diff = form.cleaned_data.get("recipe_diff")
            chart_type = form.cleaned_data.get("chart_type")

            try:
                # Use Q objects for complex queries
                q_objects = Q()

                # If recipe_name is provided, add a filter for name containing the input
                if recipe_name:
                    q_objects &= Q(name__icontains=recipe_name)
                # If ingredients is provided, add a filter for ingredients containing the input
                if ingredients:
                    q_objects &= Q(ingredients__icontains=ingredients)
                # If recipe_diff is provided, add a filter for difficulty matching the input
                if recipe_diff:
                    q_objects &= Q(difficulty=recipe_diff)

                # Filter recipes based on the constructed query
                qs = Recipe.objects.filter(q_objects)

                if qs.exists():
                    # Convert the queryset to a DataFrame for further processing
                    recipes_df = pd.DataFrame(qs.values())

                    # Generate a chart based on the selected chart type
                    chart = get_chart(
                        chart_type, recipes_df, labels=recipes_df["name"].values
                    )

                    # Convert DataFrame to HTML for rendering in the template
                    recipes_df = recipes_df.to_html()

            except Exception as e:
                # Print an error message if an exception occurs during processing
                print(f"Error: {str(e)}")

    # Render the template with the form, search results, and chart
    return render(
        request,
        "recipes/search.html",
        {"form": form, "recipes_df": recipes_df, "chart": chart},
    )


@login_required
def create_view(request):
    if request.method == "POST":
        create_form = CreateRecipeForm(request.POST, request.FILES)
        if create_form.is_valid():
            create_form.save()
            messages.success(request, "Recipe created successfully.")
            return redirect("create")
    else:
        create_form = CreateRecipeForm()

    context = {"create_form": create_form}
    return render(request, "recipes/create.html", context)

recipes/templates/recipes/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>RecipeApp | About</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'recipes/images/recipe-book.png' %}">
    <link rel='stylesheet' type='text/css' href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
      body {
        font-family: 'Lato', sans-serif;
        background-color: #eaece5;
        margin: 0;
        padding: 0;
      }

      p {
        font-size: 20px; 
        line-height: 1.6;
        color: #666;
        max-width: 800px;
        margin: auto; /* Center the paragraph */
        padding: 0 1rem;
      }

      main {
        margin: 50px auto;
        max-width: 1500px;
        text-align: center;
      }

      .about {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 1160px;
        margin: 0 auto;
      }

      .about h2 {
        color: #333;
      }

      .about p {
        color: #000000;
        line-height: 1.6;
      }

      .about a {
        display: inline-block;
        margin-top: 20px;
        padding: 10px 20px;
        background-color: #000000;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
      }

      .about a:hover {
        background-color: #45a049;
      }

      .social-media a {
        margin: 10px;
      }

      .social-media img {
        vertical-align: middle;
      }

      .page-footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: #000000;
        color: #fff;
        text-align: center;
        padding: 0 0;
      }

      footer p {
        margin-bottom: 10px;
      }

      .links {
        margin-top: 20px;
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);

      }
  
      .links p {
        font-size: 18px;
        margin-bottom: 10px;
      }
  
      .links button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #4CAF50;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
      }
  
      .links button:hover {
        background-color: #45a049;
      }      

      .grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); /* Responsive grid */
        grid-gap: 20px;
        margin: 0 auto; /* Center the grid */
        max-width: 1200px; /* Limit the width of the grid */
      }
      
      .grid__item {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        text-align: center; /* Center text */
        max-width: 100%; /* Ensure images don't exceed the grid item width */
      }
      
      .grid-img {
        max-width: 100%; /* Ensure images don't exceed the width of their container */
        height: auto; /* Maintain aspect ratio */
      }
    
      .projects-heading {
        font-size: 35px;
        color: #153098;
        margin-bottom: 20px;
        text-align: center; /* Center the heading */
      }

    </style>
    
    <body>    
      <ul>
        <li><a href="{% url 'recipes:list' %}">All Recipes</a></li>
        <li><a href="{% url 'recipes:search' %}">Search</a></li>
        <li><a href="{% url 'recipes:create' %}">Create</a></li>
        <li><a class="active" href="{% url 'recipes:about' %}">About</a></li>
        <li style="float:right"><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    <main>
        <div class="about">
            <h2><span>About Page</span></h2>
            <p>My name is Josh DeCuir, a recent graduate from the CareerFoundry Full Stack Program with a passion for coding, 
              specializing in building websites and web applications. I'm actively seeking a full-time role where 
              I can apply my skills and continue to grow. Feel free to explore my projects
              and connect with me—I look forward to hearing from you!</p>
        </div>
        <br>

        <section>
          <h2 class="projects-heading"><span>Check out some of my projects<span></h2>
          <div class="grid">
              <!-- Grid items will live here -->
              <div class="grid__item">
                  <h2>To Do List App</h2>
                  <a href="https://github.com/JoshDeCuir/to-do-list-app" target="_blank"><img src="{% static 'recipes/images/toDoListApp.jpg' %}" class="grid-img" alt="To Do List App"></a>
                  <p>
                      This is a simple to-do-list app made with JQuery.
                  </p>
                  <a href="https://github.com/JoshDeCuir/to-do-list-app" target="_blank">
                    <img src="{% static 'recipes/images/600px-Octicons-mark-github.svg.png' %}" alt="Github" height="30">
                  </a>
              </div>
              <div class="grid__item">
                  <h2>Pokedex</h2>
                  <a href="https://joshdecuir.github.io/pokemon-app/" target="_blank"><img src="{% static 'recipes/images/pokedex.jpg' %}" class="grid-img" alt="Pokedex"></a>
                  <p>
                    This is a lightweight Pokémon web application that fetches 
                    data from a public API, allowing users to view various data points.
                  </p>
                  <a href="https://github.com/JoshDeCuir/pokemon-app" target="_blank">
                    <img src="{% static 'recipes/images/600px-Octicons-mark-github.svg.png' %}" alt="Github" height="30">
                  </a>
              </div>
              <div class="grid__item">
                <h2>myFlix-Angular-client</h2>
                <a href="https://github.com/JoshDeCuir/myFlix-Angular-client" target="_blank"><img src="{% static 'recipes/images/myFlix-angular.jpg' %}" class="grid-img" alt="myFlix-angular"></a>
                <p>
                  This is the client-side of the myFlix application, built with Angular, based on its existing 
                  server-side code which includes a REST API and database
                </p>
                <a href="https://github.com/JoshDeCuir/myFlix-Angular-client" target="_blank">
                  <img src="{% static 'recipes/images/600px-Octicons-mark-github.svg.png' %}" alt="Github" height="30">
                </a>
              </div>              
              <div class="grid__item">
                  <h2>myFlix-React-client</h2>
                  <a href="https://myflix-application.netlify.app/login" target="_blank"><img src="{% static 'recipes/images/myFlix-react.jpg' %}" class="grid-img" alt="myFlix-react"></a>
                  <p>
                    This is the client-side of the myFlix app, developed with React, and integrated with the existing 
                    server-side code, including a REST API and database.
                  </p>
                  <a href="https://github.com/KunKang82/myFlix-client" target="_blank">
                    <img src="{% static 'recipes/images/600px-Octicons-mark-github.svg.png' %}" alt="Github" height="30"></a>
              </div>
              <div class="grid__item">
                <h2>Movie API</h2>                
                <a href="https://github.com/JoshDeCuir/movie_api" target="_blank"><img src="{% static 'recipes/images/movie_api.jpg' %}" class="grid-img" alt="movie-api" width="400"></a>
                <p>
                  This API is the server-side component of a movies web application. The web application provides users with access to information about different movies, the director, and genres.
                </p>
                <a href="https://github.com/JoshDeCuir/movie_api" target="_blank">
                  <img src="{% static 'recipes/images/600px-Octicons-mark-github.svg.png' %}" alt="Github" height="30">
                </a>
              </div>            
              <div class="grid__item">
                <h2>Chat app</h2>
                <a href="https://github.com/JoshDeCuir/chat-app" target="_blank"><img src="{% static 'recipes/images/ChatApp.jpg' %}" class="ChatApp" alt="grid-img" width="350"></a>
                <p>
                  A mobile chat app that offers users a messaging interface,
                  along with options to share images and their location.
                </p>
                <a href="https://github.com/JoshDeCuir/chat-app" target="_blank">
                  <img src="{% static 'recipes/images/600px-Octicons-mark-github.svg.png' %}" alt="Github" height="30">
                </a>
              </div>
              <div class="grid__item">
                    <h2>Meet app</h2>
                    <a href="https://joshdecuir.github.io/meet/" target="_blank"><img src="{% static 'recipes/images/MeetApp.jpg' %}" class="grid-img" alt="Meet App"></a>
                    <p>
                      Meet is a serverless, progressive web application (PWA) built with React, following a test-driven development approach. It integrates with the 
                      Google Calendar API to retrieve upcoming events in various cities.
                    </p>
                    <a href="https://github.com/JoshDeCuir/meet" target="_blank">
                      <img src="{% static 'recipes/images/600px-Octicons-mark-github.svg.png' %}" alt="Github" height="30">
                    </a>
                </div>
          </div>
      </section>
    </main>     

    <!-- Add Social media links -->
    <footer class="page-footer">
      <p>Find me on</p>
      <div class="social-media">          
          <a href="https://github.com/JoshDeCuir" target="_blank">
            <img src="{% static 'recipes/images/github_connection_logo_network_social_icon.png' %}" alt="Github" height="30">
          </a>
          <a href="https://www.linkedin.com/in/josh-decuir/" target="_blank">
            <img src="{% static 'recipes/images/linkedin_icon.png' %}" alt="LinkedIn" height="30" style="filter:brightness(125%);">
          </a>
          <a href="mailto:joshmdecuir@gmail.com">
            <img src="{% static 'recipes/images/email.png' %}" alt="Email" height="30" onclick="sendEmail()">
          </a>
      </div>
  </footer>
</body>

</html>

recipes/templates/recipes/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RecipeApp | Create</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/recipe-book.png' %}"
    />
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}" />
    <style type="text/css">
      body {
        font-family: "Lato", sans-serif;
        background-color: #eaece5;
        margin: 0;
        padding: 0;
      }

      .form-field label {
        display: inline-block;
        width: 150px; /* Adjust as needed for proper alignment */
        text-align: right;
        margin-right: 10px;
      }

      .form-field input,
      .form-field select {
        width: 200px; /* Adjust as needed for proper alignment */
      }

      .form-field select {
        width: 208px;
        height: 25px;
        appearance: none; /* Remove default styling in modern browsers */
      }
    </style>
  </head>

  <body>
    <ul>
      <li><a href="{% url 'recipes:list' %}">All Recipes</a></li>
      <li><a href="{% url 'recipes:search' %}">Search</a></li>
      <li><a class="active" href="{% url 'recipes:create' %}">Create</a></li>
      <li><a href="{% url 'recipes:about' %}">About</a></li>
      <li style="float: right"><a href="{% url 'logout' %}">Logout</a></li>
    </ul>

    <h1>Create a Recipe</h1>
    <h2>All fields are required.</h2>

    {% if messages %} {% for message in messages %}
    <script>
      alert("{{ message }}");
    </script>
    {% endfor %} {% endif %}

    <form
      action=""
      method="POST"
      class="form_data"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div class="form-field">
        <label for="id_name">Name:</label>
        {{ create_form.name }}
      </div>
      <div class="form-field">
        <label for="id_cooking_time">Cooking time (min):</label>
        {{ create_form.cooking_time }}
      </div>
      <div class="form-field">
        <label for="id_difficulty">Difficulty:</label>
        {{ create_form.difficulty }}
      </div>
      <div class="form-field">
        <label for="id_ingredients">Ingredients:</label>
        {{ create_form.ingredients }}
      </div>
      <div class="form-field">
        <label for="id_pic">Picture:</label>
        {{ create_form.pic }}
      </div>
      <button type="submit" class="create-btn">Create</button>
    </form>
  </body>
</html>

recipes/templates/recipes/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RecipeApp | Recipe details</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/recipe-book.png' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <style type="text/css">
      body {
        font-family: "Lato", sans-serif;
        background-color: #eaece5;
        margin: 0;
        padding: 0;
      }

      .detail {
        display: flex;
        flex-direction: column;
        align-items: center;
      }
    </style>
  </head>
  <body>
    <ul>
      <li><a href="{% url 'recipes:list' %}">All Recipes</a></li>
      <li><a href="{% url 'recipes:search' %}">Search</a></li>
      <li><a href="{% url 'recipes:create' %}">Create</a></li>
      <li><a href="{% url 'recipes:about' %}">About</a></li>
      <li style="float: right"><a href="{% url 'logout' %}">Logout</a></li>
    </ul>

    <div class="detail">
      <h1 style="text-align: center">Recipe details</h1>
      {% comment%} HTML tag for heading {% endcomment%} {% if object.pic %}
      <img src="{{object.pic.url}}" width="350" height="350" />
      {% endif %}

      <h2>Details: {{object.name}}</h2>

      <b>Recipe Name: </b> {{object.name}} <br />

      <b>Cooking Time (min): </b> {{object.cooking_time}} <br />
      <br />
      <b>Ingredients: </b> {{object.ingredients}} <br />
      <br />
      <b>Difficulty: </b> {{ object.difficulty|capfirst }} <br />
    </div>
  </body>
</html>

recipes/templates/recipes/main.html
<!DOCTYPE html>  
<html lang="en">  
  <head>
    <title>RecipeApp | All Recipes</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'recipes/images/recipe-book.png' %}">
    <link rel='stylesheet' type='text/css' href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
      body {
        font-family: 'Lato', sans-serif;
        background-color: #eaece5;
        margin: 0;
        padding: 0;
      }
    </style>


</head> 
<body>
  <ul>
    <li><a class="active" href="{% url 'recipes:list' %}">All Recipes</a></li>
    <li><a href="{% url 'recipes:search' %}">Search</a></li>
    <li><a href="{% url 'recipes:create' %}">Create</a></li>
    <li><a href="{% url 'recipes:about' %}">About</a></li>
    <li style="float:right"><a href="{% url 'logout' %}">Logout</a></li>
  </ul>
  
  <h1>Recipes' list</h1>        {% comment%} HTML tag for heading  {% endcomment%}
  
  <div class="recipe-container">
    {% for object in object_list %}
      <a href="{{ object.get_absolute_url }}" class="recipe-card">
        <h2 class="recipe-name">{{ object.name }}</h2>
        <div class="recipe-pic">
        {% if object.pic %}
          <img src="{{ object.pic.url }}" alt="{{ object.name }}">
        {% endif %}
        </div>
      </a>
    {% endfor %}
  </div>
</body>
</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RecipeApp | Home</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/recipe-book.png' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <script src="{% static 'sales/home.js' %}" defer></script>
    <style type="text/css">
      body {
        background: linear-gradient(rgba(0, 0, 0, 0.235), rgba(0, 0, 0, 0.235)),
          url("{% static 'recipes/images/recipes.jpg' %}") no-repeat fixed;
        background-size: cover;
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-top: 10vh;
        padding: 3px;
      }
    </style>
  </head>
  <body>
    <div>
      <h1>Recipe App</h1>
    </div>
    <div class="login-container">
      <h2>Log in to your account to see our list of recipes</h2>
      <div class="center-button">
        <a href="{%url 'login' %}" class="login_btn"> Login </a>
      </div>
    </div>
  </body>
</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RecipeApp | Search</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link
      rel="shortcut icon"
      href="{% static 'recipes/images/recipe-book.png' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'recipes/css/styles.css' %}"
    />
    <style type="text/css">
      body {
        font-family: "Lato", sans-serif;
        background-color: #eaece5;
        margin: 0;
        padding: 0;
      }

      .chart {
        align-items: center;
        display: flex;
        flex-direction: column;
      }
    </style>
  </head>
  <body>
    <ul>
      <li><a href="{% url 'recipes:list' %}">All Recipes</a></li>
      <li><a class="active" href="{% url 'recipes:search' %}">Search</a></li>
      <li><a href="{% url 'recipes:create' %}">Create</a></li>
      <li><a href="{% url 'recipes:about' %}">About</a></li>
      <li style="float: right"><a href="{% url 'logout' %}">Logout</a></li>
    </ul>
    <h1>Search for recipes</h1>
    <br />
    <br />
    <form action="" method="POST" class="form_data" id="search-form">
      {% csrf_token %} {{form}}
      <button type="submit" class="search-btn">Search</button>
      <a href="{% url 'recipes:search' %}" class="reset-btn">Reset Search</a>
    </form>
    <br />
    <br />
    <div class="chart">
      {% if recipes_df%} {{recipes_df|safe}}
      <br />
      <br />
      <img src="data:image/png;base64, {{chart|safe}}" />
      {% else %}
      <h3>No Data</h3>
      {% endif %}
    </div>
  </body>
</html>